<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Daily extends Model
{
    protected $guarded = [];

    protected $table = 'wechat_daily';

    public function staff()
    {
        return $this->belongsTo(Staff::class);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model){
            $result=self::where('staff_id',$model->staff_id)->wherebetween('created_at',[Carbon::today(),Carbon::tomorrow()])->exists();
            if ($result){
                throw new \Exception('今日日志已完成，请勿重复提交！！');
            }
        });
    }
}
